-- =============================================================================
-- 01_foundation.sql — Database, schemas, RBAC, and core registry tables
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- Database
CREATE OR REPLACE DATABASE SELFHEALING_PROD;

-- Schemas
CREATE SCHEMA IF NOT EXISTS SELFHEALING_PROD.BRONZE;
CREATE SCHEMA IF NOT EXISTS SELFHEALING_PROD.SILVER;
CREATE SCHEMA IF NOT EXISTS SELFHEALING_PROD.GOLD;
CREATE SCHEMA IF NOT EXISTS SELFHEALING_PROD.CONFIG;

USE SCHEMA SELFHEALING_PROD.CONFIG;

-- Schema Registry: known-good baseline of source schemas
CREATE OR REPLACE TABLE SCHEMA_REGISTRY (
    TABLE_CATALOG    VARCHAR,
    TABLE_SCHEMA     VARCHAR,
    TABLE_NAME       VARCHAR,
    COLUMN_NAME      VARCHAR,
    DATA_TYPE        VARCHAR,
    ORDINAL_POSITION NUMBER,
    IS_NULLABLE      VARCHAR,
    REGISTERED_AT    TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_SCHEMA_REGISTRY PRIMARY KEY (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME)
);

-- Schema Change Events: detected drift
CREATE OR REPLACE TABLE SCHEMA_CHANGE_EVENTS (
    EVENT_ID         VARCHAR DEFAULT UUID_STRING(),
    CHANGE_TYPE      VARCHAR,  -- NEW_COLUMN, COLUMN_DROP, TYPE_CHANGE, NEW_TABLE
    TABLE_SCHEMA     VARCHAR,
    TABLE_NAME       VARCHAR,
    COLUMN_NAME      VARCHAR,
    OLD_DATA_TYPE    VARCHAR,
    NEW_DATA_TYPE    VARCHAR,
    BRANCH_NAME      VARCHAR,
    PR_URL           VARCHAR,
    PIPELINE_STATUS  VARCHAR DEFAULT 'PENDING',  -- PENDING, CODE_GENERATED, PR_OPEN, CI_PASSED, CI_FAILED, RESOLVED
    DETECTED_AT      TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    RESOLVED_AT      TIMESTAMP_LTZ
);

-- Pipeline Health Audit: data quality findings
CREATE OR REPLACE TABLE PIPELINE_HEALTH_AUDIT (
    AUDIT_ID         VARCHAR DEFAULT UUID_STRING(),
    CHECK_TYPE       VARCHAR,  -- NULL_FK_RATE, ORPHAN_FK, DUPLICATE_SK, SCHEMA_DRIFT, PATH_COVERAGE
    TABLE_NAME       VARCHAR,
    COLUMN_NAME      VARCHAR,
    SEVERITY         VARCHAR,  -- CRITICAL, WARNING, INFO
    METRIC_VALUE     NUMBER(10,4),
    THRESHOLD        NUMBER(10,4),
    DIAGNOSIS        VARIANT,  -- AI-generated root cause analysis
    STATUS           VARCHAR DEFAULT 'OPEN',  -- OPEN, ACKNOWLEDGED, RESOLVED
    DETECTED_AT      TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    RESOLVED_AT      TIMESTAMP_LTZ
);

-- Pipeline Baselines: expected metrics for comparison
CREATE OR REPLACE TABLE PIPELINE_BASELINES (
    TABLE_NAME       VARCHAR,
    METRIC_NAME      VARCHAR,
    BASELINE_VALUE   NUMBER(10,4),
    UPDATED_AT       TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_BASELINES PRIMARY KEY (TABLE_NAME, METRIC_NAME)
);

-- Artifact Registry: dbt model lineage graph
CREATE OR REPLACE TABLE ARTIFACT_REGISTRY (
    ARTIFACT_NAME    VARCHAR,
    ARTIFACT_SCHEMA  VARCHAR,  -- BRONZE, SILVER, GOLD
    FILE_PATH        VARCHAR,
    DEPENDS_ON       VARCHAR,  -- parent artifact name
    MATERIALIZATION  VARCHAR DEFAULT 'TABLE',
    REGISTERED_AT    TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Generated Code: LLM-regenerated SQL for impacted models
CREATE OR REPLACE TABLE GENERATED_CODE (
    EVENT_ID         VARCHAR,
    ARTIFACT_NAME    VARCHAR,
    FILE_PATH        VARCHAR,
    ORIGINAL_SQL     VARCHAR,
    GENERATED_SQL    VARCHAR,
    TEST_STATUS      VARCHAR,  -- PENDING, PASS, FAIL
    TEST_ERROR       VARCHAR,
    GENERATED_AT     TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Warehouse for pipeline execution
CREATE WAREHOUSE IF NOT EXISTS SELFHEALING_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE SELFHEALING_WH;

GRANT USAGE ON DATABASE SELFHEALING_PROD TO ROLE ACCOUNTADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SELFHEALING_PROD TO ROLE ACCOUNTADMIN;
