-- =============================================================================
-- 01_foundation.sql — Database, schemas, RBAC, and core registry tables
-- Production-hardened: custom roles, IF NOT EXISTS, retention policies
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- Roles: least privilege
CREATE ROLE IF NOT EXISTS SELFHEALING_ADMIN;
CREATE ROLE IF NOT EXISTS SELFHEALING_EXECUTOR;
GRANT ROLE SELFHEALING_EXECUTOR TO ROLE SELFHEALING_ADMIN;
GRANT ROLE SELFHEALING_ADMIN TO ROLE ACCOUNTADMIN;

-- Database (safe — will not drop existing)
CREATE DATABASE IF NOT EXISTS SELFHEALING_PROD;

-- Schemas
CREATE SCHEMA IF NOT EXISTS SELFHEALING_PROD.BRONZE;
CREATE SCHEMA IF NOT EXISTS SELFHEALING_PROD.SILVER;
CREATE SCHEMA IF NOT EXISTS SELFHEALING_PROD.GOLD;
CREATE SCHEMA IF NOT EXISTS SELFHEALING_PROD.CONFIG;

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS SELFHEALING_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

-- Grants
GRANT USAGE ON DATABASE SELFHEALING_PROD TO ROLE SELFHEALING_ADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SELFHEALING_PROD TO ROLE SELFHEALING_ADMIN;
GRANT ALL ON ALL SCHEMAS IN DATABASE SELFHEALING_PROD TO ROLE SELFHEALING_ADMIN;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE SELFHEALING_PROD TO ROLE SELFHEALING_ADMIN;
GRANT CREATE VIEW ON ALL SCHEMAS IN DATABASE SELFHEALING_PROD TO ROLE SELFHEALING_ADMIN;
GRANT CREATE PROCEDURE ON SCHEMA SELFHEALING_PROD.CONFIG TO ROLE SELFHEALING_ADMIN;
GRANT CREATE FUNCTION ON SCHEMA SELFHEALING_PROD.CONFIG TO ROLE SELFHEALING_ADMIN;
GRANT USAGE ON WAREHOUSE SELFHEALING_WH TO ROLE SELFHEALING_ADMIN;
GRANT USAGE ON WAREHOUSE SELFHEALING_WH TO ROLE SELFHEALING_EXECUTOR;
GRANT SELECT ON ALL TABLES IN DATABASE SELFHEALING_PROD TO ROLE SELFHEALING_EXECUTOR;

USE ROLE SELFHEALING_ADMIN;
USE WAREHOUSE SELFHEALING_WH;
USE SCHEMA SELFHEALING_PROD.CONFIG;

-- Schema Registry: known-good baseline of source schemas
CREATE TABLE IF NOT EXISTS SCHEMA_REGISTRY (
    TABLE_CATALOG    VARCHAR,
    TABLE_SCHEMA     VARCHAR,
    TABLE_NAME       VARCHAR,
    COLUMN_NAME      VARCHAR,
    DATA_TYPE        VARCHAR,
    ORDINAL_POSITION NUMBER,
    IS_NULLABLE      VARCHAR,
    REGISTERED_AT    TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_SCHEMA_REGISTRY PRIMARY KEY (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME)
);

-- Schema Change Events: detected drift
CREATE TABLE IF NOT EXISTS SCHEMA_CHANGE_EVENTS (
    EVENT_ID         VARCHAR DEFAULT UUID_STRING(),
    CHANGE_TYPE      VARCHAR NOT NULL,
    TABLE_SCHEMA     VARCHAR NOT NULL,
    TABLE_NAME       VARCHAR NOT NULL,
    COLUMN_NAME      VARCHAR,
    OLD_DATA_TYPE    VARCHAR,
    NEW_DATA_TYPE    VARCHAR,
    BRANCH_NAME      VARCHAR,
    PR_URL           VARCHAR,
    PIPELINE_STATUS  VARCHAR DEFAULT 'PENDING',
    DETECTED_AT      TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    RESOLVED_AT      TIMESTAMP_LTZ,
    CONSTRAINT UQ_EVENT UNIQUE (CHANGE_TYPE, TABLE_NAME, COLUMN_NAME, PIPELINE_STATUS)
)
DATA_RETENTION_TIME_IN_DAYS = 30;

-- Pipeline Health Audit: data quality findings
CREATE TABLE IF NOT EXISTS PIPELINE_HEALTH_AUDIT (
    AUDIT_ID         VARCHAR DEFAULT UUID_STRING(),
    CHECK_TYPE       VARCHAR NOT NULL,
    TABLE_NAME       VARCHAR NOT NULL,
    COLUMN_NAME      VARCHAR,
    SEVERITY         VARCHAR NOT NULL,
    METRIC_VALUE     NUMBER(10,4),
    THRESHOLD        NUMBER(10,4),
    DIAGNOSIS        VARIANT,
    STATUS           VARCHAR DEFAULT 'OPEN',
    DETECTED_AT      TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    RESOLVED_AT      TIMESTAMP_LTZ
)
DATA_RETENTION_TIME_IN_DAYS = 90;

-- Pipeline Run Log: execution observability
CREATE TABLE IF NOT EXISTS PIPELINE_RUN_LOG (
    RUN_ID           VARCHAR DEFAULT UUID_STRING(),
    STARTED_AT       TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT     TIMESTAMP_LTZ,
    STEP             VARCHAR,
    STATUS           VARCHAR,
    DETAILS          VARCHAR,
    DURATION_MS      NUMBER,
    DRY_RUN          BOOLEAN DEFAULT FALSE
);

-- Pipeline Baselines: expected metrics for comparison
CREATE TABLE IF NOT EXISTS PIPELINE_BASELINES (
    TABLE_NAME       VARCHAR,
    METRIC_NAME      VARCHAR,
    BASELINE_VALUE   NUMBER(10,4),
    UPDATED_AT       TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_BASELINES PRIMARY KEY (TABLE_NAME, METRIC_NAME)
);

-- Artifact Registry: dbt model lineage graph
CREATE TABLE IF NOT EXISTS ARTIFACT_REGISTRY (
    ARTIFACT_NAME    VARCHAR NOT NULL,
    ARTIFACT_SCHEMA  VARCHAR NOT NULL,
    FILE_PATH        VARCHAR NOT NULL,
    DEPENDS_ON       VARCHAR NOT NULL,
    MATERIALIZATION  VARCHAR DEFAULT 'TABLE',
    REGISTERED_AT    TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_ARTIFACT PRIMARY KEY (ARTIFACT_NAME, DEPENDS_ON)
);

-- Generated Code: LLM-regenerated SQL for impacted models
CREATE TABLE IF NOT EXISTS GENERATED_CODE (
    EVENT_ID         VARCHAR NOT NULL,
    ARTIFACT_NAME    VARCHAR NOT NULL,
    ARTIFACT_SCHEMA  VARCHAR,
    FILE_PATH        VARCHAR,
    ORIGINAL_SQL     VARCHAR,
    GENERATED_SQL    VARCHAR,
    TEST_STATUS      VARCHAR DEFAULT 'PENDING',
    TEST_ERROR       VARCHAR,
    GENERATED_AT     TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UQ_GENERATED UNIQUE (EVENT_ID, ARTIFACT_NAME)
)
DATA_RETENTION_TIME_IN_DAYS = 30;
