-- =============================================================================
-- 07_pipeline_tasks.sql — Orchestration: scheduled tasks + master pipeline proc
-- =============================================================================

USE SCHEMA SELFHEALING_PROD.CONFIG;

-- Master orchestrator: runs the full pipeline end-to-end
CREATE OR REPLACE PROCEDURE SP_RUN_PIPELINE()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_result VARCHAR;
    v_halt VARCHAR;
    v_event_id VARCHAR;
    v_diag VARCHAR;
    v_codegen VARCHAR;
    v_validate VARCHAR;
    v_pr VARCHAR;
BEGIN
    -- Step 1: Detect drift
    CALL SP_SCHEMA_DRIFT_DETECTOR();

    -- Step 2: Run health checks
    CALL SP_PIPELINE_HEALTH_CHECK();

    -- Step 3: Check halt gate
    CALL SP_HALT_GATE() INTO v_halt;
    IF (LEFT(v_halt, 6) = 'CLEAR') THEN
        RETURN 'Pipeline clear — no issues detected.';
    END IF;

    -- Step 4: Diagnose pending issues
    CALL SP_DIAGNOSE_PENDING() INTO v_diag;

    -- Step 5: For each pending schema event, generate code + open PR
    FOR rec IN (
        SELECT EVENT_ID, CHANGE_TYPE, TABLE_NAME, COLUMN_NAME
        FROM SCHEMA_CHANGE_EVENTS
        WHERE PIPELINE_STATUS = 'PENDING'
        ORDER BY DETECTED_AT
        LIMIT 1  -- process one at a time
    ) DO
        v_event_id := rec.EVENT_ID;

        -- Generate code
        CALL SP_GENERATE_ARTIFACT_CODE(:v_event_id) INTO v_codegen;

        -- Validate against DEV clone
        CALL SP_VALIDATE_GENERATED_CODE(:v_event_id) INTO v_validate;

        -- Build PR body with diagnosis + validation results
        LET v_diagnosis_text VARCHAR := '';
        SELECT COALESCE(DIAGNOSIS:root_cause::VARCHAR, 'No diagnosis available')
        INTO v_diagnosis_text
        FROM PIPELINE_HEALTH_AUDIT
        WHERE TABLE_NAME = rec.TABLE_NAME AND CHECK_TYPE = 'SCHEMA_DRIFT'
        ORDER BY DETECTED_AT DESC LIMIT 1;

        LET v_test_summary VARCHAR := '';
        SELECT LISTAGG(
            CASE WHEN TEST_STATUS = 'PASS' THEN '✅ ' ELSE '❌ ' END || ARTIFACT_NAME || 
            CASE WHEN TEST_ERROR IS NOT NULL THEN ' — ' || LEFT(TEST_ERROR, 100) ELSE '' END,
            '\n'
        ) INTO v_test_summary
        FROM GENERATED_CODE WHERE EVENT_ID = :v_event_id;

        LET v_branch VARCHAR := 'self-heal/' || LOWER(rec.CHANGE_TYPE) || '-' || LOWER(rec.TABLE_NAME) || '-' || LOWER(COALESCE(rec.COLUMN_NAME, 'table'));
        LET v_title VARCHAR := 'Self-Heal: ' || rec.CHANGE_TYPE || ' on ' || rec.TABLE_NAME || '.' || COALESCE(rec.COLUMN_NAME, '*');
        LET v_body VARCHAR := '## Self-Healing Pipeline — Automated PR\n\n' ||
            '### Change Detected\n' ||
            '- **Type:** ' || rec.CHANGE_TYPE || '\n' ||
            '- **Table:** ' || rec.TABLE_NAME || '\n' ||
            '- **Column:** ' || COALESCE(rec.COLUMN_NAME, 'N/A') || '\n\n' ||
            '### AI Diagnosis\n' || v_diagnosis_text || '\n\n' ||
            '### Validation Results\n```\n' || v_test_summary || '\n```\n\n' ||
            '### Action Required\n' ||
            'Review the generated code changes and merge if correct. ' ||
            'The pipeline is HALTED until this PR is merged or the event is resolved.\n\n' ||
            '---\n*Generated by Self-Healing Pipeline (Cortex AI)*';

        -- Open PR
        CALL SP_OPEN_GITHUB_PR(:v_event_id, 'sfc-gh-cabdelnour/selfhealing-pipeline', v_branch, v_title, v_body) INTO v_pr;

        -- Post validation results as comment
        LET v_pr_url VARCHAR := '';
        SELECT PR_URL INTO v_pr_url FROM SCHEMA_CHANGE_EVENTS WHERE EVENT_ID = :v_event_id;
        IF (v_pr_url IS NOT NULL AND v_pr_url != '') THEN
            LET v_comment VARCHAR := '## CI Validation Results\n\n' || v_validate || '\n\n```\n' || v_test_summary || '\n```';
            CALL SP_POST_PR_COMMENT('sfc-gh-cabdelnour/selfhealing-pipeline', :v_pr_url, :v_comment);
        END IF;
    END FOR;

    RETURN 'Pipeline executed — ' || v_halt || ' | ' || COALESCE(v_codegen, 'no codegen') || ' | ' || COALESCE(v_validate, 'no validation') || ' | ' || COALESCE(v_pr, 'no PR');
END;
$$;

-- Procedure: Resolve an event (advance baseline, mark resolved)
CREATE OR REPLACE PROCEDURE SP_RESOLVE_EVENT(p_event_id VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_table_name VARCHAR;
    v_change_type VARCHAR;
    v_column_name VARCHAR;
    v_new_type VARCHAR;
BEGIN
    SELECT TABLE_NAME, CHANGE_TYPE, COLUMN_NAME, NEW_DATA_TYPE
    INTO v_table_name, v_change_type, v_column_name, v_new_type
    FROM SCHEMA_CHANGE_EVENTS WHERE EVENT_ID = :p_event_id;

    -- Advance SCHEMA_REGISTRY baseline
    IF (v_change_type = 'NEW_COLUMN') THEN
        INSERT INTO SCHEMA_REGISTRY (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE, ORDINAL_POSITION, IS_NULLABLE)
        SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE, ORDINAL_POSITION, IS_NULLABLE
        FROM SELFHEALING_PROD.INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = 'BRONZE' AND TABLE_NAME = :v_table_name AND COLUMN_NAME = :v_column_name;
    ELSEIF (v_change_type = 'COLUMN_DROP') THEN
        DELETE FROM SCHEMA_REGISTRY WHERE TABLE_NAME = :v_table_name AND COLUMN_NAME = :v_column_name;
    ELSEIF (v_change_type = 'TYPE_CHANGE') THEN
        UPDATE SCHEMA_REGISTRY SET DATA_TYPE = :v_new_type WHERE TABLE_NAME = :v_table_name AND COLUMN_NAME = :v_column_name;
    END IF;

    -- Mark event resolved
    UPDATE SCHEMA_CHANGE_EVENTS SET PIPELINE_STATUS = 'RESOLVED', RESOLVED_AT = CURRENT_TIMESTAMP() WHERE EVENT_ID = :p_event_id;

    -- Mark related health audit findings
    UPDATE PIPELINE_HEALTH_AUDIT SET STATUS = 'RESOLVED', RESOLVED_AT = CURRENT_TIMESTAMP()
    WHERE TABLE_NAME = :v_table_name AND COLUMN_NAME = :v_column_name AND STATUS = 'OPEN';

    RETURN 'Event ' || :p_event_id || ' resolved. Baseline advanced.';
END;
$$;

-- Scheduled task: runs every 15 minutes
CREATE OR REPLACE TASK TASK_SELF_HEALING_PIPELINE
    WAREHOUSE = SELFHEALING_WH
    SCHEDULE = '15 MINUTE'
    ALLOW_OVERLAPPING_EXECUTION = FALSE
AS
    CALL SP_RUN_PIPELINE();

-- Task starts suspended — activate when ready to demo
ALTER TASK TASK_SELF_HEALING_PIPELINE SUSPEND;
