-- =============================================================================
-- 08_seed_demo.sql — Demo source data + artifact registry + schema baseline
-- =============================================================================

USE SCHEMA SELFHEALING_PROD.BRONZE;

-- Demo tables: simple e-commerce pattern
CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, CITY, STATE) VALUES
(1, 'Alice', 'Smith', 'alice@example.com', 'Sacramento', 'CA'),
(2, 'Bob', 'Jones', 'bob@example.com', 'Los Angeles', 'CA'),
(3, 'Carol', 'White', 'carol@example.com', 'San Diego', 'CA'),
(4, 'Dave', 'Brown', 'dave@example.com', 'San Francisco', 'CA'),
(5, 'Eve', 'Davis', 'eve@example.com', 'Oakland', 'CA');

CREATE OR REPLACE TABLE ORDERS (
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER,
    ORDER_DATE DATE,
    TOTAL_AMOUNT NUMBER(10,2),
    CURRENCY VARCHAR DEFAULT 'USD',
    STATUS VARCHAR
);

INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT, STATUS) VALUES
(101, 1, '2026-07-01', 125.50, 'COMPLETED'),
(102, 2, '2026-07-02', 89.99, 'COMPLETED'),
(103, 1, '2026-07-05', 210.00, 'SHIPPED'),
(104, 3, '2026-07-10', 45.00, 'COMPLETED'),
(105, 4, '2026-07-12', 320.75, 'PENDING'),
(106, 5, '2026-07-15', 67.50, 'COMPLETED'),
(107, 2, '2026-07-18', 155.00, 'SHIPPED'),
(108, 3, '2026-07-20', 92.00, 'COMPLETED'),
(109, 1, '2026-07-22', 450.00, 'PENDING'),
(110, 4, '2026-07-25', 78.25, 'COMPLETED');

CREATE OR REPLACE TABLE ORDER_ITEMS (
    ITEM_ID NUMBER,
    ORDER_ID NUMBER,
    PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2)
);

INSERT INTO ORDER_ITEMS (ITEM_ID, ORDER_ID, PRODUCT_NAME, CATEGORY, QUANTITY, UNIT_PRICE) VALUES
(1001, 101, 'Wireless Mouse', 'Electronics', 2, 25.00),
(1002, 101, 'USB-C Cable', 'Accessories', 3, 12.50),
(1003, 102, 'Notebook Stand', 'Office', 1, 89.99),
(1004, 103, 'Monitor 27"', 'Electronics', 1, 210.00),
(1005, 104, 'Desk Lamp', 'Office', 1, 45.00),
(1006, 105, 'Mechanical Keyboard', 'Electronics', 1, 150.00),
(1007, 105, 'Webcam HD', 'Electronics', 1, 85.75),
(1008, 105, 'Headset', 'Electronics', 1, 85.00),
(1009, 106, 'Notebook', 'Office', 5, 13.50),
(1010, 107, 'External SSD 1TB', 'Electronics', 1, 155.00),
(1011, 108, 'Whiteboard Markers', 'Office', 4, 8.00),
(1012, 108, 'Sticky Notes', 'Office', 10, 6.00),
(1013, 109, 'Standing Desk', 'Furniture', 1, 450.00),
(1014, 110, 'Mouse Pad XL', 'Accessories', 1, 35.00),
(1015, 110, 'Cable Organizer', 'Accessories', 2, 21.63);

-- Build SILVER models
USE SCHEMA SELFHEALING_PROD.SILVER;

CREATE OR REPLACE VIEW CUSTOMERS AS
SELECT CUSTOMER_ID, UPPER(TRIM(FIRST_NAME)) AS FIRST_NAME, UPPER(TRIM(LAST_NAME)) AS LAST_NAME,
       LOWER(TRIM(EMAIL)) AS EMAIL, UPPER(TRIM(CITY)) AS CITY, UPPER(TRIM(STATE)) AS STATE, CREATED_AT
FROM SELFHEALING_PROD.BRONZE.CUSTOMERS;

CREATE OR REPLACE VIEW ORDERS AS
SELECT ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT, CURRENCY, UPPER(TRIM(STATUS)) AS STATUS
FROM SELFHEALING_PROD.BRONZE.ORDERS;

CREATE OR REPLACE VIEW ORDER_ITEMS AS
SELECT ITEM_ID, ORDER_ID, TRIM(PRODUCT_NAME) AS PRODUCT_NAME, UPPER(TRIM(CATEGORY)) AS CATEGORY,
       QUANTITY, UNIT_PRICE
FROM SELFHEALING_PROD.BRONZE.ORDER_ITEMS;

-- Build GOLD models
USE SCHEMA SELFHEALING_PROD.GOLD;

CREATE OR REPLACE TABLE ORDERS_DAILY AS
SELECT o.ORDER_DATE, COUNT(DISTINCT o.ORDER_ID) AS ORDER_COUNT,
       SUM(o.TOTAL_AMOUNT) AS DAILY_REVENUE, COUNT(DISTINCT o.CUSTOMER_ID) AS UNIQUE_CUSTOMERS
FROM SELFHEALING_PROD.SILVER.ORDERS o
GROUP BY o.ORDER_DATE;

CREATE OR REPLACE TABLE CATEGORY_SUMMARY AS
SELECT oi.CATEGORY, COUNT(DISTINCT oi.ORDER_ID) AS ORDER_COUNT,
       SUM(oi.QUANTITY) AS TOTAL_UNITS, SUM(oi.QUANTITY * oi.UNIT_PRICE) AS TOTAL_REVENUE
FROM SELFHEALING_PROD.SILVER.ORDER_ITEMS oi
GROUP BY oi.CATEGORY;

-- Seed the SCHEMA_REGISTRY baseline
USE SCHEMA SELFHEALING_PROD.CONFIG;

INSERT INTO SCHEMA_REGISTRY (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE, ORDINAL_POSITION, IS_NULLABLE)
SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE, ORDINAL_POSITION, IS_NULLABLE
FROM SELFHEALING_PROD.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'BRONZE';

-- Seed the ARTIFACT_REGISTRY (dbt lineage graph)
INSERT INTO ARTIFACT_REGISTRY (ARTIFACT_NAME, ARTIFACT_SCHEMA, FILE_PATH, DEPENDS_ON) VALUES
-- SILVER depends on BRONZE
('CUSTOMERS', 'SILVER', 'dbt/models/silver/customers.sql', 'CUSTOMERS'),
('ORDERS', 'SILVER', 'dbt/models/silver/orders.sql', 'ORDERS'),
('ORDER_ITEMS', 'SILVER', 'dbt/models/silver/order_items.sql', 'ORDER_ITEMS'),
-- GOLD depends on SILVER
('ORDERS_DAILY', 'GOLD', 'dbt/models/gold/orders_daily.sql', 'ORDERS'),
('CATEGORY_SUMMARY', 'GOLD', 'dbt/models/gold/category_summary.sql', 'ORDER_ITEMS');

-- Store original model SQL in GENERATED_CODE for future regeneration reference
INSERT INTO GENERATED_CODE (EVENT_ID, ARTIFACT_NAME, FILE_PATH, ORIGINAL_SQL, GENERATED_SQL, TEST_STATUS) VALUES
('BASELINE', 'CUSTOMERS', 'dbt/models/silver/customers.sql',
 'SELECT CUSTOMER_ID, UPPER(TRIM(FIRST_NAME)) AS FIRST_NAME, UPPER(TRIM(LAST_NAME)) AS LAST_NAME, LOWER(TRIM(EMAIL)) AS EMAIL, UPPER(TRIM(CITY)) AS CITY, UPPER(TRIM(STATE)) AS STATE, CREATED_AT FROM {{ source(''bronze'', ''CUSTOMERS'') }}',
 'SELECT CUSTOMER_ID, UPPER(TRIM(FIRST_NAME)) AS FIRST_NAME, UPPER(TRIM(LAST_NAME)) AS LAST_NAME, LOWER(TRIM(EMAIL)) AS EMAIL, UPPER(TRIM(CITY)) AS CITY, UPPER(TRIM(STATE)) AS STATE, CREATED_AT FROM {{ source(''bronze'', ''CUSTOMERS'') }}',
 'PASS'),
('BASELINE', 'ORDERS', 'dbt/models/silver/orders.sql',
 'SELECT ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT, CURRENCY, UPPER(TRIM(STATUS)) AS STATUS FROM {{ source(''bronze'', ''ORDERS'') }}',
 'SELECT ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT, CURRENCY, UPPER(TRIM(STATUS)) AS STATUS FROM {{ source(''bronze'', ''ORDERS'') }}',
 'PASS'),
('BASELINE', 'ORDER_ITEMS', 'dbt/models/silver/order_items.sql',
 'SELECT ITEM_ID, ORDER_ID, TRIM(PRODUCT_NAME) AS PRODUCT_NAME, UPPER(TRIM(CATEGORY)) AS CATEGORY, QUANTITY, UNIT_PRICE FROM {{ source(''bronze'', ''ORDER_ITEMS'') }}',
 'SELECT ITEM_ID, ORDER_ID, TRIM(PRODUCT_NAME) AS PRODUCT_NAME, UPPER(TRIM(CATEGORY)) AS CATEGORY, QUANTITY, UNIT_PRICE FROM {{ source(''bronze'', ''ORDER_ITEMS'') }}',
 'PASS'),
('BASELINE', 'ORDERS_DAILY', 'dbt/models/gold/orders_daily.sql',
 'SELECT o.ORDER_DATE, COUNT(DISTINCT o.ORDER_ID) AS ORDER_COUNT, SUM(o.TOTAL_AMOUNT) AS DAILY_REVENUE, COUNT(DISTINCT o.CUSTOMER_ID) AS UNIQUE_CUSTOMERS FROM {{ ref(''ORDERS'') }} o GROUP BY o.ORDER_DATE',
 'SELECT o.ORDER_DATE, COUNT(DISTINCT o.ORDER_ID) AS ORDER_COUNT, SUM(o.TOTAL_AMOUNT) AS DAILY_REVENUE, COUNT(DISTINCT o.CUSTOMER_ID) AS UNIQUE_CUSTOMERS FROM {{ ref(''ORDERS'') }} o GROUP BY o.ORDER_DATE',
 'PASS'),
('BASELINE', 'CATEGORY_SUMMARY', 'dbt/models/gold/category_summary.sql',
 'SELECT oi.CATEGORY, COUNT(DISTINCT oi.ORDER_ID) AS ORDER_COUNT, SUM(oi.QUANTITY) AS TOTAL_UNITS, SUM(oi.QUANTITY * oi.UNIT_PRICE) AS TOTAL_REVENUE FROM {{ ref(''ORDER_ITEMS'') }} oi GROUP BY oi.CATEGORY',
 'SELECT oi.CATEGORY, COUNT(DISTINCT oi.ORDER_ID) AS ORDER_COUNT, SUM(oi.QUANTITY) AS TOTAL_UNITS, SUM(oi.QUANTITY * oi.UNIT_PRICE) AS TOTAL_REVENUE FROM {{ ref(''ORDER_ITEMS'') }} oi GROUP BY oi.CATEGORY',
 'PASS');
